/**
 * Pixel art do gato. Cada frame é uma grade ASCII desenhada virada para a DIREITA
 * (o componente espelha o sprite quando o gato anda para a esquerda).
 *
 * Legenda (os índices da paleta ficam em palette.ts):
 *   .  transparente     k  contorno          s  contorno suave (dobras, pescoço)
 *   w  pelo             g  sombra do pelo
 *   a  olho             p  rosa (nariz, língua, almofadinhas)
 *
 * `ax` é a coluna do centro do corpo: é ela que fica alinhada à posição X do gato,
 * então trocar de pose ou de lado não faz o sprite "pular". A última linha é o chão —
 * por isso uma linha vazia no fim levanta o desenho um pixel (é o pulinho da corrida).
 *
 * Este arquivo não importa nada (nem tipos) para poder ser lido direto pelo Node
 * no script de exportação da spritesheet.
 */

export interface FrameDef {
  /** Coluna âncora (centro do corpo). */
  readonly ax: number;
  /** Linhas da grade, de cima para baixo. Todas com o mesmo comprimento. */
  readonly rows: readonly string[];
}

export const FRAMES = {
  // ── Sentado (o desenho original) ──────────────────────────────────────────
  sit: { ax: 13, rows: [
    '............k....k..',
    '...........kwk..kwk.',
    '..........kwgkkkwgk.',
    '..........kggwwwggk.',
    '.........kwwwwwwwwwk',
    '.........kwwwwwwwwwk',
    '.........kwwwawwwawk',
    '.........kwwwawwwawk',
    '..........kwwwwpwwwk',
    '........kkwwwwwwwwk.',
    '.kk....kwwwgggggwk..',
    '.kwkkkkkwwkggggwwk..',
    '..kwwwgwwwgkkkwkwk..',
    '...kkkkkgwgwwkwkwk..',
    '........kkkkkkkkk...',
  ]},
  sitBlink: { ax: 13, rows: [
    '............k....k..',
    '...........kwk..kwk.',
    '..........kwgkkkwgk.',
    '..........kggwwwggk.',
    '.........kwwwwwwwwwk',
    '.........kwwwwwwwwwk',
    '.........kwwwwwwwwwk',
    '.........kwwwkwwwkwk',
    '..........kwwwwpwwwk',
    '........kkwwwwwwwwk.',
    '.kk....kwwwgggggwk..',
    '.kwkkkkkwwkggggwwk..',
    '..kwwwgwwwgkkkwkwk..',
    '...kkkkkgwgwwkwkwk..',
    '........kkkkkkkkk...',
  ]},
  sitTail: { ax: 13, rows: [
    '............k....k..',
    '...........kwk..kwk.',
    '..........kwgkkkwgk.',
    '..........kggwwwggk.',
    '.........kwwwwwwwwwk',
    '.........kwwwwwwwwwk',
    '.........kwwwawwwawk',
    '.........kwwwawwwawk',
    '..........kwwwwpwwwk',
    '.kk.....kkwwwwwwwwk.',
    '.kwk...kwwwgggggwk..',
    '.kwkkkkkwwkggggwwk..',
    '..kwwwgwwwgkkkwkwk..',
    '...kkkkkgwgwwkwkwk..',
    '........kkkkkkkkk...',
  ]},
  meow: { ax: 13, rows: [
    '............k....k..',
    '...........kwk..kwk.',
    '..........kwgkkkwgk.',
    '..........kggwwwggk.',
    '.........kwwwwwwwwwk',
    '.........kwwwwwwwwwk',
    '.........kwwwwwwwwwk',
    '.........kwwwkwwwkwk',
    '..........kwwwwpwwwk',
    '........kkwwwwwkwwk.',
    '.kk....kwwwgggggwk..',
    '.kwkkkkkwwkggggwwk..',
    '..kwwwgwwwgkkkwkwk..',
    '...kkkkkgwgwwkwkwk..',
    '........kkkkkkkkk...',
  ]},
  yawn: { ax: 13, rows: [
    '............k....k..',
    '...........kwk..kwk.',
    '..........kwgkkkwgk.',
    '..........kggwwwggk.',
    '.........kwwwwwwwwwk',
    '.........kwwwwwwwwwk',
    '.........kwwwwwwwwwk',
    '.........kwwwkwwwkwk',
    '..........kwwwwpwwwk',
    '........kkwwwwkpkwk.',
    '.kk....kwwwggggkwk..',
    '.kwkkkkkwwkggggwwk..',
    '..kwwwgwwwgkkkwkwk..',
    '...kkkkkgwgwwkwkwk..',
    '........kkkkkkkkk...',
  ]},

  // ── Se limpando: lambe a pata e esfrega o rosto ───────────────────────────
  lick: { ax: 13, rows: [
    '............k....k..',
    '...........kwk..kwk.',
    '..........kwgkkkwgk.',
    '..........kggwwwggk.',
    '.........kwwwwwwwwwk',
    '.........kwwwwwwwwwk',
    '.........kwwwwwwwwwk',
    '.........kwwwkwwwkwk',
    '..........kwwwwpwwwk',
    '........kkwwwwwpkkk.',
    '.kk....kwwwggggkwwk.',
    '.kwkkkkkwwkggggwwk..',
    '..kwwwgwwwgkkkwkk...',
    '...kkkkkgwgwwkwk....',
    '........kkkkkkkk....',
  ]},
  lickUp: { ax: 13, rows: [
    '............k....k..',
    '...........kwk..kwk.',
    '..........kwgkkkwgk.',
    '..........kggwwwggk.',
    '.........kwwwwwwwwwk',
    '.........kwwwwwwwwwk',
    '.........kwwwwwwwwwk',
    '.........kwwwkwwwkwk',
    '..........kwwwwpwwwk',
    '........kkwwwwwwkkk.',
    '.kk....kwwwggggkwwk.',
    '.kwkkkkkwwkggggwwk..',
    '..kwwwgwwwgkkkwkk...',
    '...kkkkkgwgwwkwk....',
    '........kkkkkkkk....',
  ]},
  wash: { ax: 13, rows: [
    '............k....k..',
    '...........kwk..kwk.',
    '..........kwgkkkwgk.',
    '..........kggwwwggk.',
    '.........kwwwwwwwwwk',
    '.........kwwwwwwwkkk',
    '.........kwwwwwwkwwk',
    '.........kwwwkwwkwwk',
    '..........kwwwwpkwkk',
    '........kkwwwwwwkwk.',
    '.kk....kwwwggggkwk..',
    '.kwkkkkkwwkggggwwk..',
    '..kwwwgwwwgkkkwkk...',
    '...kkkkkgwgwwkwk....',
    '........kkkkkkkk....',
  ]},

  // Corpo com costas em arco, traseiro e peito arredondados e barriga recolhida.
  stand: { ax: 12, rows: [
    '..............k....k..',
    '.............kwk..kwk.',
    '.k..........kwgkkkwgk.',
    'kwk.........kggwwwggk.',
    'kwk........kwwwwwwwwwk',
    '.kwk.......kwwwwwwwwwk',
    '..kwk.kkkkkkwwwawwwawk',
    '...kwkwwwwwkwwwawwwawk',
    '....kwwwwwwwkwwwwpwwwk',
    '...kwwwwwwwwwwwwwwwwk.',
    '...kwwwwwwgggggggwwk..',
    '....kwwgkkkkkkgggwwk..',
    '....kgkwk.....kgkwk...',
    '....kgkwk.....kgkwk...',
    '....kkkkk.....kkkkk...',
  ]},
  // O rabo muda de desenho a cada passo: sobe e enrola no A, cai e varre no B.
  walkA: { ax: 12, rows: [
    '..............k....k..',
    '.............kwk..kwk.',
    '.kk.........kwgkkkwgk.',
    'kwwk........kggwwwggk.',
    'kwk........kwwwwwwwwwk',
    '.kwk.......kwwwwwwwwwk',
    '..kwk.kkkkkkwwwawwwawk',
    '...kwkwwwwwkwwwawwwawk',
    '....kwwwwwwwkwwwwpwwwk',
    '...kwwwwwwwwwwwwwwwwk.',
    '...kwwwwwwgggggggwwk..',
    '....kwwgkkkkkkgggwwk..',
    '....kwkgk.....kgkwk...',
    '..kwk.kgk....kgk.kwk..',
    '..kkk.kkk....kkk.kkk..',
  ]},
  walkB: { ax: 12, rows: [
    '..............k....k..',
    '.............kwk..kwk.',
    '............kwgkkkwgk.',
    '.k..........kggwwwggk.',
    'kwk........kwwwwwwwwwk',
    'kwk........kwwwwwwwwwk',
    '.kwwk.kkkkkkwwwawwwawk',
    '...kwkwwwwwkwwwawwwawk',
    '....kwwwwwwwkwwwwpwwwk',
    '...kwwwwwwwwwwwwwwwwk.',
    '...kwwwwwwgggggggwwk..',
    '....kwwgkkkkkkgggwwk..',
    '....kgkwk.....kwkgk...',
    '..kgk.kwk....kwk.kgk..',
    '..kkk.kkk....kkk.kkk..',
  ]},
  /** Galope: pernas recolhidas embaixo do corpo, rabo esticado para trás. */
  gather: { ax: 12, rows: [
    '..............k....k..',
    '.............kwk..kwk.',
    '............kwgkkkwgk.',
    '............kggwwwggk.',
    '.kk........kwwwwwwwwwk',
    'kwwk.......kwwwwwwwwwk',
    '.kwwk.kkkkkkwwwawwwawk',
    '...kwkwwwwwkwwwawwwawk',
    '....kwwwwwwwkwwwwpwwwk',
    '...kwwwwwwwwwwwwwwwwk.',
    '...kwwwwwwgggggggwwk..',
    '....kwwgkkkkkkgggwwk..',
    '....kkkgkwkkgkwkkkk...',
    '......kgkwkkgkwk......',
    '......kkkkkkkkkk......',
  ]},

  /** No ar: patas esticadas para frente e para trás, rabo voando atrás. */
  leap: { ax: 12, rows: [
    '..............k....k..',
    '.............kwk..kwk.',
    '............kwgkkkwgk.',
    '............kggwwwggk.',
    '.kk........kwwwwwwwwwk',
    'kwwk.......kwwwwwwwwwk',
    '.kwwk.kkkkkkwwwawwwawk',
    '...kwkwwwwwkwwwawwwawk',
    '....kwwwwwwwkwwwwpwwwk',
    '...kwwwwwwwwwwwwwwwwk.',
    '...kwwwwwwgggggggwwk..',
    '.kkkkwwgkkkkkkgggwwkk.',
    'kwwwkkkkkkkkkkkkkkwwwk',
    '.kkk..............kkk.',
  ]},

  // ── Correndo (galope) ─────────────────────────────────────────────────────
  // Quatro tempos de um galope: empurra com as traseiras, voa esticado, aterrissa
  // nas dianteiras e voa recolhido. Nos dois voos o desenho sobe (linhas vazias
  // embaixo), que é o pulinho de cada passada.
  runA: { ax: 12, rows: [
    '..............k....k..',
    '.............kwk..kwk.',
    '............kwgkkkwgk.',
    '............kggwwwggk.',
    '.kk........kwwwwwwwwwk',
    'kwwk.......kwwwwwwwwwk',
    '.kwwk.kkkkkkwwwawwwawk',
    '...kwkwwwwwkwwwawwwawk',
    '....kwwwwwwwkwwwwpwwwk',
    '...kwwwwwwwwwwwwwwwwk.',
    '...kwwwwwwgggggggwwk..',
    '....kwwgkkkkkkgggwwk..',
    '...kwgk.......kwwk....',
    '..kwwk.........kkk....',
    '..kkk.................',
  ]},
  runB: { ax: 12, rows: [
    '..............k....k..',
    '.k...........kwk..kwk.',
    'kwk.........kwgkkkwgk.',
    'kwk.........kggwwwggk.',
    '.kwk.......kwwwwwwwwwk',
    '..kwk......kwwwwwwwwwk',
    '...kwk.kkkkkwwwawwwawk',
    '....kwkwwwwkwwwawwwawk',
    '....kwwwwwwwkwwwwpwwwk',
    '...kwwwwwwwwwwwwwwwwk.',
    '...kwwwwwwgggggggwwk..',
    '.kkkkwwgkkkkkkgggwwkk.',
    'kwwwkkkkkkkkkkkkkkwwwk',
    '.kkk..............kkk.',
    '......................',
  ]},
  runC: { ax: 12, rows: [
    '......................',
    '..............k....k..',
    '.............kwk..kwk.',
    '............kwgkkkwgk.',
    '.kk.........kggwwwggk.',
    'kwwk.......kwwwwwwwwwk',
    '.kwwk.kkkkkkwwwwwwwwwk',
    '...kwkwwwwwkwwwawwwawk',
    '....kwwwwwwkwwwawwwawk',
    '...kwwwwwwwwkwwwwpwwwk',
    '...kwwwwwwgggggggwwk..',
    '....kwwgkkkkkkgggwwk..',
    '......kwgk......kwwk..',
    '......kkkk.......kwk..',
    '.................kkk..',
  ]},
  runD: { ax: 12, rows: [
    '..............k....k..',
    '.k...........kwk..kwk.',
    'kwk.........kwgkkkwgk.',
    'kwk.........kggwwwggk.',
    '.kwk.......kwwwwwwwwwk',
    '..kwk......kwwwwwwwwwk',
    '...kwk.kkkkkwwwawwwawk',
    '....kwkwwwwkwwwawwwawk',
    '....kwwwwwwwkwwwwpwwwk',
    '...kwwwwwwwwwwwwwwwwk.',
    '...kwwwwwwgggggggwwk..',
    '....kwwgkkkkkkgggwwk..',
    '.....kwwk....kwwk.....',
    '.....kkkk....kkkk.....',
    '......................',
    '......................',
  ]},

  // Deitado (descanso, soneca e espreita antes do bote usam este mesmo corpo).
  // O rabo é comprido e fino; em `loafTail` a ponta levanta para abanar.
  loaf: { ax: 16, rows: [
    '..................k....k..',
    '.................kwk..kwk.',
    '..........kkkkk.kwgkkkwgk.',
    '........kkwwwwwwkggwwwggk.',
    '.......kwwwwwwwkwwwwwwwwwk',
    '.......kwwwwwwwkwwwwwwwwwk',
    '......kwwwwwwwwkwwwawwwawk',
    '.kkkkkkwwwwwwggkwwwawwwawk',
    'kwwwwgkwwwggggggkwwwwpwwwk',
    '.kkkkkkkkkkkkkkkkkkkkkkkk.',
  ]},
  loafTail: { ax: 16, rows: [
    '..................k....k..',
    '.................kwk..kwk.',
    '..........kkkkk.kwgkkkwgk.',
    '........kkwwwwwwkggwwwggk.',
    '.......kwwwwwwwkwwwwwwwwwk',
    '.......kwwwwwwwkwwwwwwwwwk',
    '.kk...kwwwwwwwwkwwwawwwawk',
    'kwwkkkkwwwwwwggkwwwawwwawk',
    '.kkwwgkwwwggggggkwwwwpwwwk',
    '...kkkkkkkkkkkkkkkkkkkkkk.',
  ]},
  sleep: { ax: 16, rows: [
    '..................k....k..',
    '.................kwk..kwk.',
    '..........kkkkk.kwgkkkwgk.',
    '........kkwwwwwwkggwwwggk.',
    '.......kwwwwwwwkwwwwwwwwwk',
    '.......kwwwwwwwkwwwwwwwwwk',
    '......kwwwwwwwwkwwwwwwwwwk',
    '.kkkkkkwwwwwwggkwwwkwwwkwk',
    'kwwwwgkwwwggggggkwwwwpwwwk',
    '.kkkkkkkkkkkkkkkkkkkkkkkk.',
  ]},
  /** Respiração: as costas sobem um pixel. */
  sleepBreath: { ax: 16, rows: [
    '..................k....k..',
    '...........kkkk..kwk..kwk.',
    '.........kkwwwwwkwgkkkwgk.',
    '........kwwwwwwwkggwwwggk.',
    '.......kwwwwwwwkwwwwwwwwwk',
    '.......kwwwwwwwkwwwwwwwwwk',
    '......kwwwwwwwwkwwwwwwwwwk',
    '.kkkkkkwwwwwwggkwwwkwwwkwk',
    'kwwwwgkwwwggggggkwwwwpwwwk',
    '.kkkkkkkkkkkkkkkkkkkkkkkk.',
  ]},
  /** Espreguiçando (reverência): bumbum alto, peito no chão, patas esticadas à frente. */
  stretch: { ax: 12, rows: [
    '.k......................',
    'kwk.....................',
    'kwk.....................',
    '.kwk...........k....k...',
    '..kwkkk.......kwk..kwk..',
    '..kwwwwkk....kwgkkkwgk..',
    '..kwwwwwwk...kggwwwggk..',
    '..kwwwwwwwkkkwwwwwwwwwk.',
    '..kwwwwwwwwwkwwwwwwwwwk.',
    '..kwgwwwwwwwkwwwawwwawk.',
    '...kggggggggkwwwawwwawk.',
    '...kgkwkkkkkwkwwwwpwwwk.',
    '...kgkwk....kwwwwwwwwwwk',
    '...kkkkk....kkkkkkkkkkkk',
  ]},

  // ── Brincando: patada ─────────────────────────────────────────────────────
  batUp: { ax: 13, rows: [
    '............k....k....',
    '...........kwk..kwk...',
    '..........kwgkkkwgk...',
    '..........kggwwwggk...',
    '.........kwwwwwwwwwk..',
    '.........kwwwwwwwwwk..',
    '.........kwwwawwwawk..',
    '.........kwwwawwwawk..',
    '..........kwwwwpwwwk..',
    '........kkwwwwwwwwkkk.',
    '.kk....kwwwgggggwwwwwk',
    '.kwkkkkkwwkggggwwkkkk.',
    '..kwwwgwwwgkkkwkk.....',
    '...kkkkkgwgwwkwk......',
    '........kkkkkkkk......',
  ]},
  batDown: { ax: 13, rows: [
    '............k....k....',
    '...........kwk..kwk...',
    '..........kwgkkkwgk...',
    '..........kggwwwggk...',
    '.........kwwwwwwwwwk..',
    '.........kwwwwwwwwwk..',
    '.........kwwwawwwawk..',
    '.........kwwwawwwawk..',
    '..........kwwwwpwwwk..',
    '........kkwwwwwwwwk...',
    '.kk....kwwwgggggwkk...',
    '.kwkkkkkwwkggggwwwk...',
    '..kwwwgwwwgkkkwk.kwk..',
    '...kkkkkgwgwwkwk.kwwk.',
    '........kkkkkkkk.kkkk.',
  ]},


  // ── No colo, seguro pelo cangote (visto de frente, rabo abanando) ─────────
  // No colo, seguro pelo cangote: patas da frente na frente do corpo e o rabo
  // passeando de um lado para o outro feito pêndulo (dangleA→D→A).

  // No colo, pendurado pelo cangote: corpo de frente, patinhas discretas embaixo
  // e o rabo indo de um lado para o outro feito pêndulo.
  dangleA: { ax: 8, rows: [
    '......k....k.....',
    '.....kwk..kwk....',
    '....kwgkkkwgk....',
    '....kggwwwggk....',
    '...kwwwwwwwwwk...',
    '...kwwwwwwwwwk...',
    '...kwwwawwwawk...',
    '...kwwwawwwawk...',
    '....kwwwwpwwwk...',
    '.....swwggwws....',
    '....kwwggggwwk...',
    '....kwwggggwwk...',
    '....kwwggggwwk...',
    '....kwwggggwwk...',
    '.....kwwggwwk....',
    '.....kwwwwwwk....',
    '.....kkwpkpwkk...',
    '......kkkkkkk....',
    '......kwwk.......',
    '....kwwk.........',
    '...kwk...........',
  ]},
  dangleB: { ax: 8, rows: [
    '......k....k.....',
    '.....kwk..kwk....',
    '....kwgkkkwgk....',
    '....kggwwwggk....',
    '...kwwwwwwwwwk...',
    '...kwwwwwwwwwk...',
    '...kwwwawwwawk...',
    '...kwwwawwwawk...',
    '....kwwwwpwwwk...',
    '.....swwggwws....',
    '....kwwggggwwk...',
    '....kwwggggwwk...',
    '....kwwggggwwk...',
    '....kwwggggwwk...',
    '.....kwwggwwk....',
    '.....kwwwwwwk....',
    '.....kkwpkpwkk...',
    '......kkkkkkk....',
    '......kwwk.......',
    '.....kwwk........',
    '....kwk..........',
  ]},
  dangleC: { ax: 8, rows: [
    '......k....k.....',
    '.....kwk..kwk....',
    '....kwgkkkwgk....',
    '....kggwwwggk....',
    '...kwwwwwwwwwk...',
    '...kwwwwwwwwwk...',
    '...kwwwawwwawk...',
    '...kwwwawwwawk...',
    '....kwwwwpwwwk...',
    '.....swwggwws....',
    '....kwwggggwwk...',
    '....kwwggggwwk...',
    '....kwwggggwwk...',
    '....kwwggggwwk...',
    '.....kwwggwwk....',
    '.....kwwwwwwk....',
    '.....kkwpkpwkk...',
    '......kkkkkkk....',
    '.......kwwk......',
    '........kwwk.....',
    '..........kwk....',
  ]},
  dangleD: { ax: 8, rows: [
    '......k....k.....',
    '.....kwk..kwk....',
    '....kwgkkkwgk....',
    '....kggwwwggk....',
    '...kwwwwwwwwwk...',
    '...kwwwwwwwwwk...',
    '...kwwwawwwawk...',
    '...kwwwawwwawk...',
    '....kwwwwpwwwk...',
    '.....swwggwws....',
    '....kwwggggwwk...',
    '....kwwggggwwk...',
    '....kwwggggwwk...',
    '....kwwggggwwk...',
    '.....kwwggwwk....',
    '.....kwwwwwwk....',
    '.....kkwpkpwkk...',
    '......kkkkkkk....',
    '.......kwwk......',
    '.........kwwk....',
    '...........kwk...',
  ]},
} satisfies Record<string, FrameDef>;

/** Efeitos pequenos (células de 8×8), sempre com as cores da paleta original. */
export const FX_FRAMES = {
  heart: { ax: 3, rows: [
    '.kk.kk.',
    'kwpkppk',
    'kpppppk',
    '.kpppk.',
    '..kpk..',
    '...k...',
  ]},
  zzz: { ax: 3, rows: [
    'kkkkkk',
    'kwwwwk',
    'kkkwk.',
    '.kwkkk',
    'kwwwwk',
    'kkkkkk',
  ]},
  dust: { ax: 2, rows: [
    '.gg..',
    'gwwgg',
    '.gwwg',
  ]},
  alert: { ax: 1, rows: [
    'kkk',
    'kwk',
    'kwk',
    'kwk',
    'kkk',
    'kwk',
    'kkk',
  ]},
} satisfies Record<string, FrameDef>;
